---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tinyauth
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: tinyauth-secret
    creationPolicy: Owner
    template:
      data:
        TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID: "{{ .POCKETID_CLIENT_ID }}"
        TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET: "{{ .POCKETID_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: tinyauth
