---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      data:
        PROVISIONING_PASSWORD: "{{ .grafana_provisioning_password }}"
        OIDC_CLIENT_SECRET: "{{ .kanidm_grafana_client_secret }}"
  dataFrom:
    - extract:
        key: grafana
      rewrite:
        - regexp:
            source: "(.*)"
            target: "grafana_$1"
    - extract:
        key: kanidm
      rewrite:
        - regexp:
            source: "(.*)"
            target: "kanidm_$1"
