---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: cilium
  interval: 1h
  path: ./kubernetes/apps/kube-system/cilium/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kube-system
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-config
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: cilium
      app.kubernetes.io/component: config
  dependsOn:
    - name: cilium
  interval: 1h
  path: ./kubernetes/apps/kube-system/cilium/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kube-system
  timeout: 5m
  wait: false
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cilium-netpols
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: cilium
      app.kubernetes.io/component: netpols
  dependsOn:
    - name: cilium
  interval: 1h
  path: ./kubernetes/apps/kube-system/cilium/netpols
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: kube-system
  timeout: 5m
  wait: false
