---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
# https://fluxcd.io/flux/monitoring/alerts/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pushover
  - ./github
