---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
data:
  TIMEZONE: "Europe/Budapest"
  PUBLIC_DOMAIN: "horvathzoltan.me"

  LAN_SUBNET: "192.168.1.0/24"
  ROUTER_IP: "192.168.1.1"
  LB_IP_POOL_START: "192.168.1.15"
  LB_IP_POOL_STOP: "192.168.1.25"
  NAS_IP: "192.168.1.10"

  ENVOY_INTERNAL_IP: "192.168.1.18"
  K8S_GATEWAY_IP: "192.168.1.19"
  PLEX_IP: "192.168.1.20"

  IOT_SUBNET: "192.168.2.0/24"

  POD_CIDR: "10.244.0.0/16"
  SVC_CIDR: "10.245.0.0/16"

  CLUSTER_DNS_IP: "10.245.0.10"
