---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: resticprofile
  namespace: default
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: resticprofile

  install:
    createNamespace: true
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

    controllers:
      resticprofile:
        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          app:
            image:
              repository: ghcr.io/zhorvath83/resticprofile
              tag: 0.32.0@sha256:24f0cd280dd64ec0c944f1d6c54f6cdc79014e3568a78fbec5866b5283a211e3

            command:
              - "/bin/sh"
              - -ec
            args:
              - resticprofile schedule --all && exec /usr/bin/supercronic /resticprofile/crontab

            env:
              - name: TZ
                value: "Europe/Budapest"

              - name: RESTIC_CACHE_DIR
                value: "/tmp/resticprofile-cache"

              - name: RESTIC_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: resticprofile-secret
                    key: RESTIC_PASSWORD

              - name: RESTIC_REPOSITORY_TEMPLATE
                valueFrom:
                  secretKeyRef:
                    name: resticprofile-secret
                    key: RESTIC_REPOSITORY_TEMPLATE

              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: resticprofile-secret
                    key: AWS_ACCESS_KEY_ID

              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: resticprofile-secret
                    key: AWS_SECRET_ACCESS_KEY

              - name: HEALTHCHECK_BACKUPS_WEBHOOK
                valueFrom:
                  secretKeyRef:
                    name: resticprofile-secret
                    key: HEALTHCHECK_BACKUPS_WEBHOOK

              - name: HEALTHCHECK_BACKUPS_CHECK_WEBHOOK
                valueFrom:
                  secretKeyRef:
                    name: resticprofile-secret
                    key: HEALTHCHECK_BACKUPS_CHECK_WEBHOOK

            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

            resources:
              requests:
                cpu: 10m
                memory: 256Mi
              limits:
                memory: 1Gi

    persistence:
      state:
        type: emptyDir
        globalMounts:
          - path: /resticprofile

      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp

      profiles-yaml:
        type: configMap
        name: resticprofile-configmap
        defaultMode: 0444
        advancedMounts:
          resticprofile:
            app:
              - path: /resticprofile/profiles.yaml
                subPath: profiles.yaml
                readOnly: true

      nfs-tmp:
        type: nfs
        server: ${CONF_NFS_SRV_IP}
        path: /tmp
        globalMounts:
          - path: /mnt/nfs-tmp

      nfs-backups:
        type: nfs
        server: ${CONF_NFS_SRV_IP}
        path: /backups
        globalMounts:
          - path: /backups
            readOnly: true
