---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: volsync-secret
    creationPolicy: Owner
    template:
      data:
        KOPIA_REPOSITORY: "b2://{{ .KOPIA_B2_BUCKET }}"
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        KOPIA_B2_BUCKET: "{{ .KOPIA_B2_BUCKET }}"
        B2_ACCOUNT_ID: "{{ .B2_ACCOUNT_ID }}"
        B2_APPLICATION_KEY: "{{ .B2_APPLICATION_KEY }}"
  dataFrom:
    - extract:
        key: volsync-template
