---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/kopiamaintenance_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: KopiaMaintenance
metadata:
  name: kopia-daily-maintenance
spec:
  enabled: true
  repository:
    repository: volsync-secret
  trigger:
    schedule: "0 12 * * *"
