---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: plex-trakt-sync
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: plex-trakt-sync
  components:
    - ../../../../components/volsync
  dependsOn:
    - name: onepassword-connect
      namespace: external-secrets
    - name: democratic-csi
      namespace: kube-system
  interval: 1h
  path: ./kubernetes/apps/default/plex-trakt-sync/app
  postBuild:
    substitute:
      APP: plex-trakt-sync
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: default
  timeout: 5m
  wait: false
