---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${rsrc}-${claim}-${ts}"
  namespace: "${namespace}"
spec:
  trigger:
    manual: restore-once
  kopia:
    repository: "${rsrc}-volsync-secret"
    destinationPVC: "${claim}"
    copyMethod: Direct
    cleanupCachePVC: true
    enableFileDeletion: true
    sourceIdentity:
      sourceName: "${rsrc}"
      sourceNamespace: "${namespace}"
    previous: ${previous}
