---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync"
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-volsync-secret"
    creationPolicy: Owner
    template:
      data:
        KOPIA_REPOSITORY: "s3://{{ .KOPIA_S3_BUCKET }}"
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .ovh_s3_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ .ovh_s3_secret_key }}"
        AWS_S3_ENDPOINT: "{{ .ovh_s3_endpoint }}"
  dataFrom:
    - extract:
        key: volsync-template
    - extract:
        key: ovh
