---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${VOLSYNC_CLAIM:=${APP}}"
spec:
  accessModes:
    - "${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"
  # Enable for the next cluster recreate when provisioning a new PVC from the
  # bootstrap ReplicationDestination in replicationdestination.yaml.
  # dataSourceRef:
  #   kind: ReplicationDestination
  #   apiGroup: volsync.backube
  #   name: "${APP}-bootstrap"
  resources:
    requests:
      storage: "${VOLSYNC_CAPACITY:=1Gi}"
  storageClassName: "${VOLSYNC_STORAGECLASS:=democratic-csi-local-hostpath}"
