---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${VOLSYNC_CLAIM:=${APP}}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "${VOLSYNC_CAPACITY:=1Gi}"
  storageClassName: democratic-csi-local-hostpath
