---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pingvin-share-x
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pingvin-share-x-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: pingvin-share-x
    - extract:
        key: smtp2go
