---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pingvin-share-x
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pingvin-share-x-secret
    creationPolicy: Owner
    template:
      data:
        PINGVINSHARE_OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
        SMTP_HOSTNAME: "{{ .smtp2go_smtp_hostname }}"
        SMTP_PORT: "{{ .smtp2go_smtp_port }}"
        SMTP_FROM: "{{ .smtp2go_smtp_from }}"
        SMTP_USER: "{{ .smtp2go_smtp_user }}"
        SMTP_PASSWORD: "{{ .smtp2go_smtp_password }}"
  dataFrom:
    - extract:
        key: smtp2go
      rewrite:
        - regexp:
            source: "(.*)"
            target: "smtp2go_$1"
  data:
    - secretKey: oidc_client_secret
      remoteRef:
        key: kanidm
        property: pingvin-share-x_client_secret
