---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-wallos
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: wallos
  dependsOn:
    - name: cluster-apps-onepassword-store
    - name: cluster-apps-democratic-csi
  path: ./kubernetes/apps/default/wallos/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-ops-kubernetes
  interval: 1h
  targetNamespace: default
  timeout: 5m
  wait: false
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: wallos
      APP_UID: "1000"
      APP_GID: "1000"
      VOLSYNC_SCHEDULE: "35 3 * * *"
