---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/tuppr.home-operations.com/kubernetesupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
  name: kubernetes
spec:
  kubernetes:
    # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
    version: "v1.36.1"
  talosctl:
    image:
      # renovate: datasource=custom.talos-factory depName=siderolabs/talos
      tag: "v1.13.3"
  healthChecks:
    - apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      name: ALL
      expr: object.status.conditions.filter(c, c.type == 'Ready').all(c, c.status == 'True')
      timeout: 5m
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: ALL
      expr: object.status.conditions.filter(c, c.type == 'Ready').all(c, c.status == 'True')
      timeout: 5m
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cilium
      namespace: kube-system
      expr: object.status.conditions.filter(c, c.type == 'Ready').all(c, c.status == 'True')
      timeout: 5m
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cloudflare-tunnel
      namespace: networking
      expr: object.status.conditions.filter(c, c.type == 'Ready').all(c, c.status == 'True')
      timeout: 5m
