---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: paperless
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: paperless
  dependsOn:
    - name: onepassword-connect
    - name: democratic-csi
  path: ./kubernetes/apps/default/paperless/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  targetNamespace: default
  timeout: 5m
  wait: false
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: paperless
      APP_UID: "1000"
      APP_GID: "1000"
      VOLSYNC_CAPACITY: "20Gi"
      VOLSYNC_CACHE: "2Gi"
      VOLSYNC_RETAIN_DAILY: "7"
      VOLSYNC_RETAIN_WEEKLY: "4"
      VOLSYNC_RETAIN_MONTHLY: "12"
