---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-connect-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: onepassword-connect-credentials
    creationPolicy: Owner
    template:
      data:
        1password-credentials.json: "{{ .credentials }}"
  dataFrom:
    - extract:
        key: 1password-connect-kubernetes
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-connect-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: onepassword-connect-token
    creationPolicy: Owner
    template:
      data:
        token: "{{ .token }}"
  dataFrom:
    - extract:
        key: 1password-connect-kubernetes
