---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: selfhosted
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./actual/ks.yaml
  - ./backrest/ks.yaml
  - ./home-gallery/ks.yaml
  - ./homepage/ks.yaml
  - ./mealie/ks.yaml
  - ./open-webui/ks.yaml
  - ./paperless/ks.yaml
  - ./paperless-gpt/ks.yaml
  - ./pingvin-share-x/ks.yaml
  - ./resticprofile/ks.yaml
  - ./searxng/ks.yaml
  - ./wallos/ks.yaml
