{
 "title": "Flux Cluster Stats",
 "tags": [ "flux" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Kustomizations",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{kind=~\"Kustomization\"})"
    }
   ]
  },
  {
   "title": "HelmReleases",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{kind=~\"HelmRelease\"})"
    }
   ]
  },
  {
   "title": "GitRepositories",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gotk_resource_info{kind=~\"GitRepository\"})"
    }
   ]
  },
  {
   "title": "Flux Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "gotk_resource_info" }
   ]
  }
 ]
}