---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crowdsec-web-ui
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: crowdsec-web-ui-secret
    creationPolicy: Owner
    template:
      data:
        CONFIG_INSTANCE_LAPI_AUTH_PASSWORD: "{{ .WEBUI_LAPI_PASSWORD }}"
        CONFIG_AUTH_OIDC_CLIENT_SECRET: "{{ .oidc_client_secret }}"
  dataFrom:
    - extract:
        key: crowdsec
  data:
    - secretKey: oidc_client_secret
      remoteRef:
        key: pocket-id-clients
        property: crowdsec-web-ui_client_secret
