---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-connect
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: onepassword-connect
  dependsOn:
    - name: external-secrets
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: onepassword-connect
      namespace: external-secrets
  path: ./kubernetes/apps/external-secrets/onepassword-connect/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  interval: 1h
  targetNamespace: external-secrets
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-store
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: external-secrets
  dependsOn:
    - name: external-secrets
    - name: onepassword-connect
  path: ./kubernetes/apps/external-secrets/onepassword-connect/stores/onepassword
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: external-secrets.io/v1
      kind: ClusterSecretStore
      name: onepassword
  healthCheckExprs:
    - apiVersion: external-secrets.io/v1
      kind: ClusterSecretStore
      failed: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'False')
      current: status.conditions.filter(e, e.type == 'Ready').all(e, e.status == 'True')
  interval: 1h
  targetNamespace: external-secrets
  timeout: 10m
  wait: false
