---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: isponsorblocktv
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: isponsorblocktv
  values:
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 127.0.0.1
          - 10.245.0.10
        options:
          - {name: ndots, value: "1"}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
        sysctls:
          - {name: net.ipv4.ip_unprivileged_port_start, value: "53"}
    controllers:
      isponsorblocktv:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/dmunozv04/isponsorblocktv
              tag: v2.9.0@sha256:5b8cfa805cb60b99a9e83a2df62d41c63865a315f7ee7cfed1a78052d93650b6
            env:
              TZ: "Europe/Budapest"
            probes:
              liveness: {enabled: false}
              readiness: {enabled: false}
              startup: {enabled: false}
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 1m
                memory: 50Mi
              limits:
                memory: 128Mi
          ctrld:
            image:
              repository: docker.io/controldns/ctrld
              tag: 1.5.0@sha256:0fa146d1952cad23c5db7d703c0b4c8fa276f6eae9f50f50adcbc3306dd1ff65
            args:
              - -vv
              - --listen
              - 0.0.0.0:53
              - --primary_upstream
              - https://dns.controld.com/$(CTRLD_RESOLVER_ID)
            env:
              CTRLD_RESOLVER_ID:
                valueFrom:
                  secretKeyRef:
                    name: isponsorblocktv-secret
                    key: CTRLD_RESOLVER_ID
            probes:
              liveness: {enabled: false}
              readiness: {enabled: false}
              startup: {enabled: false}
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 5m
                memory: 32Mi
              limits:
                memory: 64Mi
    persistence:
      data:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          isponsorblocktv:
            app:
              - path: /app/data
      ctrld-etc:
        type: emptyDir
        advancedMounts:
          isponsorblocktv:
            ctrld:
              - path: /etc/controld
      ctrld-tmp:
        type: emptyDir
        advancedMounts:
          isponsorblocktv:
            ctrld:
              - path: /tmp
