---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-rebuildable
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: democratic-csi-local-hostpath
