---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/_/persistentvolumeclaim_v1.json
# Shared PVC for Plex rebuildable data:
# cache, metadata artwork, and scanner assets.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-rebuildable
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: democratic-csi-local-hostpath
