function envoy_on_request(request_handle)
  local user_agent = request_handle:headers():get("user-agent") or ""
  local blocked_patterns = {
    "AI2Bot",
    "AI2Bot-DeepResearchEval",
    "AddSearchBot",
    "AgentTimes",
    "Ai2Bot-Dolma",
    "AmazonBuyForMe",
    "Amazonbot",
    "Amzn-SearchBot",
    "Amzn-User",
    "Andibot",
    "Anomura",
    "ApifyBot",
    "ApifyWebsiteContentCrawler",
    "Applebot",
    "Applebot-Extended",
    "Aranet-SearchBot",
    "Awario",
    "AzureAI-SearchBot",
    "Bravebot",
    "Brightbot",
    "Brightbot 1.0",
    "BuddyBot",
    "Bytespider",
    "CCBot",
    "Channel3Bot",
    "ChatGLM-Spider",
    "ChatGPT Agent",
    "ChatGPT-User",
    "Claude-Code",
    "Claude-SearchBot",
    "Claude-User",
    "Claude-Web",
    "ClaudeBot",
    "CloudVertexBot",
    "Cloudflare-AutoRAG",
    "Code",
    "Cotoyogi",
    "CragCrawler",
    "Crawl4AI",
    "Crawlspace",
    "Cursor",
    "Datenbank Crawler",
    "DeepSeekBot",
    "Devin",
    "Diffbot",
    "DuckAssistBot",
    "Echobot Bot",
    "EchoboxBot",
    "ExaBot",
    "FacebookBot",
    "Factset_spyderbot",
    "FirecrawlAgent",
    "FriendlyCrawler",
    "GPTBot",
    "GeistHaus-PageFetcher",
    "Gemini-Deep-Research",
    "Google-Agent",
    "Google-CloudVertexBot",
    "Google-Extended",
    "Google-Firebase",
    "Google-Gemini-CLI",
    "Google-NotebookLM",
    "GoogleAgent-Mariner",
    "GoogleAgent-URLContext",
    "GoogleOther",
    "GoogleOther-Image",
    "GoogleOther-Video",
    "HenkBot",
    "ICC-Crawler",
    "ISSCyberRiskCrawler",
    "IbouBot",
    "ImagesiftBot",
    "Kangaroo Bot",
    "Kimi-User",
    "KlaviyoAIBot",
    "KunatoCrawler",
    "LAIONDownloader",
    "LCC",
    "LinerBot",
    "Linguee Bot",
    "LinkupBot",
    "Manus-User",
    "Meta-ExternalAgent",
    "Meta-ExternalFetcher",
    "MistralAI-User",
    "MistralAI-User/1.0",
    "MyCentralAIScraperBot",
    "NagetBot",
    "NotebookLM",
    "NovaAct",
    "OAI-SearchBot",
    "OpenAI",
    "Operator",
    "PanguBot",
    "Panscient",
    "Perplexity-User",
    "PerplexityBot",
    "PetalBot",
    "PhindBot",
    "Poggio-Citations",
    "Poseidon Research Crawler",
    "QualifiedBot",
    "Querit-SearchBot",
    "QueritBot",
    "QuillBot",
    "SBIntuitionsBot",
    "Scrapy",
    "SemrushBot-OCOB",
    "SemrushBot-SWA",
    "Shap-User",
    "ShapBot",
    "Sidetrade indexer bot",
    "Spider",
    "TavilyBot",
    "Terra Cotta",
    "TerraCotta",
    "Thinkbot",
    "TikTokSpider",
    "Timpibot",
    "Trae",
    "TwinAgent",
    "UseAI",
    "VelenPublicWebCrawler",
    "WARDBot",
    "WRTNBot",
    "Webzio-Extended",
    "YaK",
    "YandexAdditional",
    "YandexAdditionalBot",
    "YouBot",
    "ZanistaBot",
    "aiHitBot",
    "amazon-kendra",
    "anthropic-ai",
    "atlassian-bot",
    "bedrockbot",
    "bigsur.ai",
    "cohere-ai",
    "cohere-training-data-crawler",
    "facebookexternalhit",
    "iAskBot",
    "iaskspider",
    "iaskspider/2.0",
    "imageSpider",
    "img2dataset",
    "kagi-fetcher",
    "laion-huggingface-processor",
    "meta-externalagent",
    "meta-externalfetcher",
    "meta-webindexer",
    "netEstate Imprint Crawler",
    "newsai",
    "omgili",
    "omgilibot",
    "opencode",
    "panscient.com",
    "quillbot.com",
    "webzio-extended",
    "wpbot"
  }

  for _, pattern in ipairs(blocked_patterns) do
    if string.find(user_agent, pattern, 1, true) then
      request_handle:logWarn("blocked bot UA: " .. pattern)
      request_handle:respond({[":status"] = "200"}, "")
      return
    end
  end
end
