---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kopia-secret
    creationPolicy: Owner
    template:
      data:
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        repository.config: |-
          {
            "storage": {
              "type": "s3",
              "config": {
                "bucket": "{{ .KOPIA_S3_BUCKET }}",
                "endpoint": "s3.eu-west-par.io.cloud.ovh.net",
                "accessKeyID": "{{ .AWS_ACCESS_KEY_ID }}",
                "secretAccessKey": "{{ .AWS_SECRET_ACCESS_KEY }}"
              }
            },
            "hostname": "volsync.volsync-system.svc.cluster.local",
            "username": "volsync",
            "description": "volsync",
            "enableActions": false
          }
  dataFrom:
    - extract:
        key: volsync-template
