---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kopia-secret
    creationPolicy: Owner
    template:
      data:
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        repository.config: |-
          {
            "storage": {
              "type": "s3",
              "config": {
                "bucket": "{{ .KOPIA_S3_BUCKET }}",
                "endpoint": "{{ .ovh_s3_endpoint }}",
                "accessKeyID": "{{ .ovh_s3_access_key }}",
                "secretAccessKey": "{{ .ovh_s3_secret_key }}"
              }
            },
            "hostname": "volsync.volsync-system.svc.cluster.local",
            "username": "volsync",
            "description": "volsync",
            "enableActions": false
          }
  dataFrom:
    - extract:
        key: volsync-template
    - extract:
        key: ovh
