---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopia
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kopia-secret
    creationPolicy: Owner
    template:
      data:
        KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
        repository.config: |-
          {
            "storage": {
              "type": "b2",
              "config": {
                "bucket": "{{ .KOPIA_B2_BUCKET }}",
                "keyID": "{{ .B2_ACCOUNT_ID }}",
                "key": "{{ .B2_APPLICATION_KEY }}"
              }
            },
            "hostname": "volsync.volsync-system.svc.cluster.local",
            "username": "volsync",
            "description": "volsync",
            "enableActions": false
          }
  dataFrom:
    - extract:
        key: volsync-template
