---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: nas-smartctl
spec:
  jobName: nas-smartctl
  staticConfigs:
    - targets:
        - "${NAS_IP}:9633"
  relabelings:
    - targetLabel: instance
      replacement: nas
      action: replace
  metricRelabelings:
    - sourceLabels:
        - __name__
      regex: "^go_.*"
      action: drop
