---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: subsyncarr
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: subsyncarr
  components:
    - ../../../../components/forward-auth
  dependsOn:
    - name: tinyauth
      namespace: security
  interval: 1h
  path: ./kubernetes/apps/downloads/subsyncarr/app
  postBuild:
    substitute:
      APP: subsyncarr
      APP_UID: "1000"
      APP_GID: "1000"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: downloads
  timeout: 5m
  wait: false
