---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-oidc
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: ${APP}-oidc-secret
    creationPolicy: Owner
    template:
      data:
        client-id: ${APP}
        client-secret: "{{ .clientSecret }}"
  data:
    - secretKey: clientSecret
      remoteRef:
        key: kanidm
        property: ${APP}_client_secret
