---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crowdsec
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./crowdsec/ks.yaml
  - ./bouncer/ks.yaml
  - ./web-ui/ks.yaml
  - ./blocklist-import/ks.yaml
