---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./envoy.yaml
  - ./gateway-external.yaml
  - ./gateway-internal.yaml
  - ./gateway-policies.yaml
  - ./security-headers.yaml
  - ./ciliumnetworkpolicy-external.yaml
  - ./ciliumnetworkpolicy-internal.yaml
  - ./observability.yaml

configMapGenerator:
  - name: envoy-external-extensions
    files:
      - resources/block-user-agents.lua

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
