---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pocket-id-secret
    creationPolicy: Owner
    template:
      data:
        ENCRYPTION_KEY: "{{ .POCKET_ID_ENCRYPTION_KEY }}"
        MAXMIND_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
  dataFrom:
    - extract:
        key: pocket-id
    - extract:
        key: maxmind
