---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pocket-id
  namespace: security
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: pocket-id
  values:
    controllers:
      pocket-id:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/pocket-id/pocket-id
              tag: v2.4.0@sha256:3e790c5d4fd82ff276b1c2bc3242be9da13cff204a2b937768ea1eba1e892571

            env:
              TZ: "Europe/Budapest"
              ANALYTICS_DISABLED: true
              APP_URL: https://id.${PUBLIC_DOMAIN}
              DB_PROVIDER: sqlite
              EMAILS_VERIFIED: true
              KEYS_STORAGE: database
              # UI_CONFIG_DISABLED: true
              SESSION_DURATION: 43800
              TRUST_PROXY: true
              UPLOAD_PATH: /app/data/uploads
              GEOLITE_DB_PATH: /app/data/GeoLite2-City.mmdb

            envFrom:
              - secretRef:
                  name: pocket-id-secret

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 1411
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness: *probes

            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }

            resources:
              requests:
                cpu: 10m
                memory: 30Mi
              limits:
                memory: 256Mi

    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: ${APP_UID}
        runAsGroup: ${APP_GID}
        fsGroup: ${APP_GID}
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

    service:
      app:
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - "id.${PUBLIC_DOMAIN}"
        parentRefs:
          - name: envoy-external
            namespace: networking
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      data:
        existingClaim: *app
        globalMounts:
          - path: /app/data
      tmpfs:
        type: emptyDir
        advancedMounts:
          pocket-id:
            app:
              - path: /tmp
                subPath: tmp
