---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.35.0/mutatingadmissionpolicybinding-admissionregistration-v1beta1.json
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: volsync-mover-jitter
spec:
  policyName: volsync-mover-jitter
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.35.0/mutatingadmissionpolicy-admissionregistration-v1beta1.json
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingAdmissionPolicy
metadata:
  name: volsync-mover-jitter
spec:
  matchConstraints:
    resourceRules:
      - apiGroups:
          - batch
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - jobs
  matchConditions:
    - name: has-volsync-job-name-prefix
      expression: object.metadata.name.startsWith("volsync-src-")
    - name: has-no-jitter-init-container
      expression: >-
        !has(object.spec.template.spec.initContainers) ||
        !object.spec.template.spec.initContainers.exists(c, c.name == "jitter")
  failurePolicy: Fail
  reinvocationPolicy: IfNeeded
  mutations:
    - patchType: JSONPatch
      jsonPatch:
        expression: >-
          has(object.spec.template.spec.initContainers)
          ? [
              JSONPatch{
                op: "add",
                path: "/spec/template/spec/initContainers/-",
                value: Object.spec.template.spec.initContainers{
                  name: "jitter",
                  image: "docker.io/library/busybox:latest",
                  imagePullPolicy: "IfNotPresent",
                  command: [
                    "sh",
                    "-c",
                    "sleep $(shuf -i 0-1800 -n 1)"
                  ]
                }
              }
            ]
          : [
              JSONPatch{
                op: "add",
                path: "/spec/template/spec/initContainers",
                value: []
              },
              JSONPatch{
                op: "add",
                path: "/spec/template/spec/initContainers/-",
                value: Object.spec.template.spec.initContainers{
                  name: "jitter",
                  image: "docker.io/library/busybox:latest",
                  imagePullPolicy: "IfNotPresent",
                  command: [
                    "sh",
                    "-c",
                    "sleep $(shuf -i 0-1800 -n 1)"
                  ]
                }
              }
            ]
