---
name: Find deprecated Kubernetes resources

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"

permissions:
  contents: read
  issues: write

jobs:
  scan-deprecated-kube-resources:
    name: Scanning deprecated Kubernetes resources
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: false

      - name: Download Pluto
        uses: FairwindsOps/pluto/github-action@5f85d3f5474aede69f17f71d3e0a36674b8b8b62 # master

      - name: Use pluto
        run: |
          pluto detect-files -d kubernetes --output wide

      - name: Create Issue on Failed workflow
        if: failure()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_TITLE: "Action workflow failed."
          FAILED_RUN_URL: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          CODEBASE_URL: "https://github.com/${{ github.repository }}/tree/${{ github.sha }}"
          WORKFLOW_NAME: ${{ github.workflow }}
          JOB_NAME: ${{ github.job }}
          JOB_STATUS: ${{ job.status }}
        run: |-
          # shellcheck disable=SC2016
          BODY=$(printf '### Context\n[Failed Run](%s)\n[Codebase](%s)\nWorkflow name - `%s`\nJob -           `%s`\nstatus -        `%s`' \
            "$FAILED_RUN_URL" "$CODEBASE_URL" "$WORKFLOW_NAME" "$JOB_NAME" "$JOB_STATUS")
          gh issue create --title "$ISSUE_TITLE" --body "$BODY" --assignee zhorvath83
