---
- resources:
    # change backend to 'kubernetes' to use Kubernetes integration. Requires RBAC.
    backend: kubernetes
    expanded: true
    cpu: true
    memory: true
- search:
    provider: duckduckgo
    target: _blank
    focus: false
    showSearchSuggestions: true
- datetime:
    text_size: xl
    locale: hu
    format:
      # dateStyle: short
      timeStyle: short
      hourCycle: h23
- openweathermap:
    # Budapest city center
    latitude: 47.50
    longitude: 19.05
    provider: openweathermap
    units: metric
    cache: 5
    format:
      maximumFractionDigits: 0
